# Generated by Django 5.2.8 on 2025-11-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The official name of the attraction (e.g., Philippine Eagle Center).', max_length=150, unique=True)),
                ('description', models.TextField(help_text='A detailed overview of the attraction and what visitors can expect.')),
                ('category', models.CharField(choices=[('NATURE', 'Nature & Outdoors'), ('CULTURAL', 'Culture & History'), ('FOOD', 'Food & Nightlife'), ('SHOPPING', 'Shopping & Malls')], default='NATURE', help_text='The primary category of the attraction.', max_length=50)),
                ('location', models.CharField(help_text='Physical address or area (e.g., Malagos, Calinan, or Roxas Avenue).', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Upload a photo of the attraction.', null=True, upload_to='attraction_photos/')),
                ('is_open', models.BooleanField(default=True, help_text='Indicates if the attraction is currently open to the public.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Attractions',
                'ordering': ['name'],
            },
        ),
    ]
