# Generated by Django 5.2.8 on 2025-11-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Latitude coordinate (e.g., 7.067). REQUIRED.', max_digits=9),
        ),
        migrations.AddField(
            model_name='attraction',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Longitude coordinate (e.g., 125.603). REQUIRED.', max_digits=9),
        ),
    ]
