# Generated by Django 5.2.8 on 2025-11-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=7.0686, help_text='Latitude coordinate (e.g., 7.067). REQUIRED.', max_digits=9),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=125.6063, help_text='Longitude coordinate (e.g., 125.603). REQUIRED.', max_digits=9),
        ),
    ]
