# Generated by Django 5.2.8 on 2025-11-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0005_alter_attraction_latitude_alter_attraction_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Admins must approve this before it is visible to the public.', max_length=10),
        ),
    ]
