# Generated by Django 5.2.8 on 2025-12-01 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0006_attraction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['status'], name='attractions_status_aea291_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['category'], name='attractions_categor_2f4c97_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['contributor'], name='attractions_contrib_837b00_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['created_at'], name='attractions_created_dd4c52_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['attraction', 'created_at'], name='attractions_attract_9481d5_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='attractions_user_id_3d46dd_idx'),
        ),
    ]
